### ISSUE TITLE
The import "studio" is not found

### ISSUE THREAD

**Issue by bssankaran** [dc0d/asterisk#1]
The imports "studio" is not found and the build fails like below.
package studio: unrecognized import path "studio" (import path does not begin with hostname)
package studio/persian/time: unrecognized import path "studio/persian/time" (import path does not begin with hostname)

I even searched "studio" in github and google but no luck.

Where can I get this repo?

**Comment by dc0d** [comment]
_Note_: This package is from my early Go days (with every bit of bad practice possible!).

* For Persian Calendar calculations use [persical](https://github.com/dc0d/persical).
* Anything from `studio` should be just helper functions (like `SafeCall` which is pretty much a wrapper which traps a `panic` inside a `recover` - I've lost much code when my old laptop got broken and I've created this repo to preserve what left).
* Main calculation engine is [gosweph](https://github.com/dc0d/gosweph) if you need that.

Honestly I have not much time left to attend to this project (I'll try) and after three years seems you are the first one who is using it!

And PRs are always welcome!

**Comment by dc0d** [comment]
I've tried to clean-up Go parts as much as I could (for today). Please see if it meets your needs.

**Comment by bssankaran** [comment]
Thanks a lot. I tried to build this project just to learn how to use gosweph.  I have already started using gosweph for an astrology api in golang. I will soon put it on github.

And, I will try this improved version of asterisk to get examples for gosweph usage.

I will raise PR for gosweph, if I find some improvements.

Thanks again.
